version: "3.7"
services:
  data-exporter-api:
    container_name: "data-exporter-api"
    image: iiicondor/ifps-predict-exporter:0.4.1
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGODB_HOST=host.docker.internal
  mongo:
    image: mongo:4.4.5
    container_name: "mongodb_container"
    ports:
      - "27017:27017"
#    volumes:
#       - :/data/db

